#!/bin/sh

case $1 in
  "remove")
    systemctl is-enabled --quiet cxoneflow-resolver-agent
    [ $? -eq 0 ] && systemctl disable cxoneflow-resolver-agent || :
    ;;

  "purge")
    getent passwd resolver-runtime > /dev/null
    if [ $? -eq 0 ];
    then
      echo Removing 'resolver-runtime' user
      userdel resolver-runtime
    fi

    getent passwd resolver > /dev/null
    if [ $? -eq 0 ];
    then
      echo Removing 'resolver' user/group
      userdel resolver
    fi
    ;;

  *)
    ;;

esac
